version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: prakhar
      POSTGRES_USER: prakhar
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_spring_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: prakhar
      SPRING_DATASOURCE_PASSWORD: prakhar
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

volumes:
  postgres_data: